/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/setup/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getSetupStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['createAdministrator'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledgers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listLedgers'];
    put?: never;
    post: operations['createLedger'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledgers/{ledgerId}/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getLedgerSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledgers/{ledgerId}/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listAccounts'];
    put?: never;
    post: operations['createAccount'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledgers/{ledgerId}/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listCategories'];
    put?: never;
    post: operations['createCategory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledgers/{ledgerId}/columns': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listColumns'];
    put?: never;
    post: operations['createColumn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledgers/{ledgerId}/rows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listRows'];
    put?: never;
    post: operations['createRow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/rows/{rowId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['recycleRow'];
    options?: never;
    head?: never;
    patch: operations['updateRow'];
    trace?: never;
  };
  '/rows/{rowId}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['restoreRow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/columns/{columnId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['recycleColumn'];
    options?: never;
    head?: never;
    patch: operations['updateColumn'];
    trace?: never;
  };
  '/columns/{columnId}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['restoreColumn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/functions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listFunctions'];
    put?: never;
    post: operations['createFunction'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/functions/{name}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateFunction'];
    trace?: never;
  };
  '/functions/{name}/invoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['invokeFunction'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listJobs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/jobs/{jobId}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['cancelJob'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['streamEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SetupStatus: {
      required: boolean;
    };
    SetupRequest: {
      username: string;
      password: string;
      ledgerName: string;
    };
    LoginRequest: {
      username: string;
      password: string;
    };
    Session: {
      user: {
        /** Format: uuid */
        id: string;
        username: string;
      };
      csrfToken: string;
      /** Format: date-time */
      expiresAt: string;
    };
    Ledger: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: date-time */
      createdAt: string;
    };
    AccountInput: {
      name: string;
      openingBalance: components['schemas']['Money'];
    };
    Account: components['schemas']['AccountInput'] & {
      /** Format: uuid */
      id: string;
      balance: components['schemas']['Money'];
      archived: boolean;
    };
    CategoryInput: {
      name: string;
      /** @enum {string} */
      direction: 'income' | 'expense';
    };
    Category: components['schemas']['CategoryInput'] & {
      /** Format: uuid */
      id: string;
      archived: boolean;
    };
    CellValue: string | boolean | null;
    RowInput: {
      /** Format: date */
      date: string;
      description: string;
      /** @enum {string} */
      kind: 'entry' | 'transfer' | 'note';
      amount: components['schemas']['Money'];
      /** Format: uuid */
      accountId?: string | null;
      /** Format: uuid */
      categoryId?: string | null;
      /** Format: uuid */
      transferAccountId?: string | null;
      cells: {
        [key: string]: components['schemas']['CellValue'];
      };
    };
    JournalRow: components['schemas']['RowInput'] & {
      /** Format: uuid */
      id: string;
      /** Format: int64 */
      revision: number;
      accountName?: string | null;
      categoryName?: string | null;
      transferAccountName?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    RowPage: {
      items: components['schemas']['JournalRow'][];
      nextCursor?: string | null;
      hasMore: boolean;
    };
    ColumnInput: {
      name: string;
      /** @enum {string} */
      type: 'text' | 'number' | 'date' | 'boolean' | 'option' | 'relation' | 'formula';
      decimalPlaces?: number;
      formulaSource?: string;
      formulaResultType?: string;
      formulaDependencies?: string[];
    };
    ColumnPatch: {
      name?: string;
      position?: number;
      width?: number;
    };
    Column: components['schemas']['ColumnInput'] & {
      /** Format: uuid */
      id: string;
      system: string | null;
      position: number;
      width: number;
      recycled: boolean;
    };
    LedgerSummary: {
      balance: components['schemas']['Money'];
      income: components['schemas']['Money'];
      expense: components['schemas']['Money'];
      /** Format: int64 */
      rowCount: number;
    };
    LuaFunction: {
      name: string;
      version: string;
      description: string;
      script: string;
      source: string;
      params: {
        name: string;
        /** @enum {string} */
        type: 'text' | 'number' | 'date' | 'boolean' | 'option';
        label: string;
        required: boolean;
        options?: string[];
      }[];
    };
    LuaFunctionInput: {
      /** @description Lua file content returning the function definition table. */
      source: string;
    };
    Job: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      kind: 'formula_recalc' | 'csv_import' | 'csv_export';
      /** @enum {string} */
      status: 'queued' | 'running' | 'completed' | 'failed' | 'cancelled';
      /** Format: int64 */
      done: number;
      /** Format: int64 */
      total: number;
      error?: Record<string, never> | null;
      /** Format: date-time */
      createdAt: string;
    };
    /**
     * @example 1250.00
     * @example -48.50
     * @example 0.00
     */
    Money: string;
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      code: string;
      detail?: string;
      fields?: {
        [key: string]: string;
      };
    };
  };
  responses: {
    /** @description Session is absent or expired. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Requested state conflicts with current state. */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Request fields failed validation. */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: {
    CsrfHeader: string;
    LedgerId: string;
    RowId: string;
    ColumnId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getSetupStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Whether an administrator already exists. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SetupStatus'];
        };
      };
    };
  };
  createAdministrator: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetupRequest'];
      };
    };
    responses: {
      /** @description Administrator, first ledger, and session created. */
      201: {
        headers: {
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'];
        };
      };
      409: components['responses']['Conflict'];
      422: components['responses']['ValidationError'];
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current session. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Authenticated session. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session removed. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
    };
  };
  listLedgers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active ledgers. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ledger'][];
        };
      };
    };
  };
  createLedger: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Ledger with default columns and internal accounts. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ledger'];
        };
      };
      422: components['responses']['ValidationError'];
    };
  };
  getLedgerSummary: {
    parameters: {
      query?: {
        from?: string;
        to?: string;
      };
      header?: never;
      path: {
        ledgerId: components['parameters']['LedgerId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Balance and entry-only period totals. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LedgerSummary'];
        };
      };
    };
  };
  listAccounts: {
    parameters: {
      query?: {
        includeArchived?: boolean;
      };
      header?: never;
      path: {
        ledgerId: components['parameters']['LedgerId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User-visible accounts and current balances. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Account'][];
        };
      };
    };
  };
  createAccount: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        ledgerId: components['parameters']['LedgerId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountInput'];
      };
    };
    responses: {
      /** @description Created account. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Account'];
        };
      };
    };
  };
  listCategories: {
    parameters: {
      query?: {
        includeArchived?: boolean;
      };
      header?: never;
      path: {
        ledgerId: components['parameters']['LedgerId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ledger categories. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'][];
        };
      };
    };
  };
  createCategory: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        ledgerId: components['parameters']['LedgerId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryInput'];
      };
    };
    responses: {
      /** @description Created category. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'];
        };
      };
    };
  };
  listColumns: {
    parameters: {
      query?: {
        recycled?: boolean;
      };
      header?: never;
      path: {
        ledgerId: components['parameters']['LedgerId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ordered active or recycled columns. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Column'][];
        };
      };
    };
  };
  createColumn: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        ledgerId: components['parameters']['LedgerId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ColumnInput'];
      };
    };
    responses: {
      /** @description Created custom column. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Column'];
        };
      };
    };
  };
  listRows: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
        sort?: string;
        /** @description URL-encoded JSON array of AND-combined typed filters. */
        filter?: string;
        recycled?: boolean;
      };
      header?: never;
      path: {
        ledgerId: components['parameters']['LedgerId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Keyset-paginated rows and typed cells. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RowPage'];
        };
      };
    };
  };
  createRow: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        ledgerId: components['parameters']['LedgerId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RowInput'];
      };
    };
    responses: {
      /** @description Saved row and balanced postings. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JournalRow'];
        };
      };
      422: components['responses']['ValidationError'];
    };
  };
  recycleRow: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        rowId: components['parameters']['RowId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Row moved to the recycle bin. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateRow: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        rowId: components['parameters']['RowId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RowInput'];
      };
    };
    responses: {
      /** @description Updated row and rebuilt postings. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JournalRow'];
        };
      };
    };
  };
  restoreRow: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        rowId: components['parameters']['RowId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Row restored. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  recycleColumn: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        columnId: components['parameters']['ColumnId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Column moved to the recycle bin. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      409: components['responses']['Conflict'];
    };
  };
  updateColumn: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        columnId: components['parameters']['ColumnId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ColumnPatch'];
      };
    };
    responses: {
      /** @description Updated column. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Column'];
        };
      };
    };
  };
  restoreColumn: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        columnId: components['parameters']['ColumnId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Column restored. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listFunctions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current atomically published Lua function registry, including editable source. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LuaFunction'][];
        };
      };
    };
  };
  createFunction: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LuaFunctionInput'];
      };
    };
    responses: {
      /** @description Lua script saved and registry reloaded. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LuaFunction'];
        };
      };
      409: components['responses']['Conflict'];
    };
  };
  updateFunction: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LuaFunctionInput'];
      };
    };
    responses: {
      /** @description Lua script updated and registry reloaded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LuaFunction'];
        };
      };
      409: components['responses']['Conflict'];
    };
  };
  invokeFunction: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Preview result; no row is mutated by invocation. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  listJobs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recent persistent jobs. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Job'][];
        };
      };
    };
  };
  cancelJob: {
    parameters: {
      query?: never;
      header: {
        'X-JournalSeed-CSRF': components['parameters']['CsrfHeader'];
      };
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancellation requested. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  streamEvents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authenticated job, formula, and Lua reload events. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
    };
  };
}
